export const usersTableName = 'users';

export const usersTableSQL = {
  createTable: `
    CREATE TABLE IF NOT EXISTS ${usersTableName}(  
      id int NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      balance BIGINT DEFAULT 0
    );
  `,
  createDefaultUser: `
    INSERT INTO ${usersTableName}(id)
      VALUES (1)
      ON CONFLICT (id) DO NOTHING;
  `,
  getUserBalance: `
    SELECT balance FROM users WHERE id = $1 FOR UPDATE
  `,
  updateUserBalance: `
    UPDATE users SET balance = $2 WHERE id = $1
  `
} as const;
